Add current date attribute to "show version" output
EdenGri/sonic-utilities pull request #1
Opened 2022-02-24 09:44 UTC by EdenGri

Signed-off-by: Eden Grisaro <egrisaro@nvidia.com>

#### What I did
Add current date attribute to "show version" output

#### How I did it
In sonic-utilities, in the "version" subcommand, print of the current date will be added using "date" from the "datetime" library.

#### How to verify it
call "show version" command and verify "Date" row under the "Uptime" row.

#### Previous command output (if the output of a command-line utility has changed)
admin@sonic:~$ show version
SONiC Software Version: SONiC.HEAD.32-21ea29a
Distribution: Debian 9.8
Kernel: 4.9.0-8-amd64
Build commit: 21ea29a
Build date: Fri Mar 22 01:55:48 UTC 2019
Built by: johnar@jenkins-worker-4

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1822K07815
Model Number: MSN2700-CS2FO
Hardware Rev: A1
Uptime: 14:40:15 up 3 min,  1 user,  load average: 1.26, 1.45, 0.66
...

#### New command output (if the output of a command-line utility has changed)
admin@sonic:~$ show version
SONiC Software Version: SONiC.HEAD.32-21ea29a
Distribution: Debian 9.8
Kernel: 4.9.0-8-amd64
Build commit: 21ea29a
Build date: Fri Mar 22 01:55:48 UTC 2019
Built by: johnar@jenkins-worker-4

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1822K07815
Model Number: MSN2700-CS2FO
Hardware Rev: A1
Uptime: 14:40:15 up 3 min,  1 user,  load average: 1.26, 1.45, 0.66
Date: Tue 22 Feb 2022
...

2022-02-24 09:46 UTC, dprital approved these changes

2022-02-28 14:26 UTC, noaOrMlnx requested changes
please change the branch name to something more official
add_date_show_version

2022-02-28 14:26 UTC, noaOrMlnx commented on show/main.py
> +    # The 'uptime' command displays the current time as the 1st entry "hh:mm:ss {more info}"
please change to 
Linux 'uptime' command displays the current time as the 1st entry "hh:mm:ss <more info>"
Split the output space character to remove the time from the output.

2022-02-28 14:26 UTC, noaOrMlnx commented on show/main.py
> +    sys_uptime_without_time = sys_uptime.stdout.read().strip().split(' ', 1)[1]
sys_uptime_no_time

2022-02-28 14:44 UTC, closed without merging